- arg: py-version
  val: '3.10'

- arg: ignore
  val:
    - old_diffop_primitives.py
    - generalized_debye.py
    - waveguide.py  # See issue #116 on gitlab
- arg: extension-pkg-whitelist
  val: pytential.qbx.target_specific
