name: test-conda-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- git
- scipy
- conda-forge::numpy
- conda-forge::sympy
- pocl
- islpy
- pyopencl
- python=3
- python-symengine=0.6.0
- pyfmmlib
- cython
- gmsh
